//____________________________________________________________________________
/*!
\class    genie::COHDNuInteractionListGenerator

\brief    Concrete implementations of the InteractionListGeneratorI interface.
          Generates a list of all the Interaction (= event summary) objects that
          can be generated by the COHDNu EventGenerator.

\author   Iker de Icaza <i.de-icaza-astiz \at sussex.ac.uk>
          University of Sussex

          Costas Andreopoulos <c.andreopoulos \at cern.ch>
          University of Liverpool

\created  June 30, 2020

\cpright  Copyright (c) 2003-2025, The GENIE Collaboration
          For the full text of the license visit http://copyright.genie-mc.org
*/
//____________________________________________________________________________

#ifndef _COHDNu_INTERACTION_LIST_GENERATOR_H_
#define _COHDNu_INTERACTION_LIST_GENERATOR_H_

#include "Framework/EventGen/InteractionListGeneratorI.h"

namespace genie {

class COHDNuInteractionListGenerator : public InteractionListGeneratorI {

public :

  COHDNuInteractionListGenerator();
  COHDNuInteractionListGenerator(string config);
  ~COHDNuInteractionListGenerator();

  //-- implement the InteractionListGeneratorI interface
  InteractionList * CreateInteractionList(const InitialState & init) const;

  //-- overload the Algorithm::Configure() methods to load private data
  //   members from configuration options
  void Configure(const Registry & config);
  void Configure(string config);

private:

  void LoadConfigData(void);

};

}      // genie namespace

#endif // _COHDNu_INTERACTION_LIST_GENERATOR_H_
