#
# Makefile for GENIE Neutrino Generator
#
# Costas Andreopoulos <c.andreopoulos \at cern.ch>
#

SHELL    = /bin/sh
NAME     = all
MAKEFILE = Makefile

# Include machine specific flags and locations (inc. files & libs)
#
include $(GENIE)/src/make/Make.include

PACKAGE           = Framework/Conventions
PACKAGE_ABBREV    = 
DICTIONARY        = 
LIBNAME           = 
EXTRA_EXT_LIBS    =

all     : 
install : install-inc 

# Include standard package makefile targets
#
include $(GENIE)/src/make/Make.std-package-targets

FORCE:

