#!/usr/bin/env bash
#!/bin/bash
export CMAKEBINDIR=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport
export PATH=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/cmake-3.6.1/bin:$PATH
#export PYTHIA6=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/pythia6/v6_424/lib
#export LD_LIBRARY_PATH=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/pythia6/v6_424/lib:$LD_LIBRARY_PATH
export PYTHIA6=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/pythia6_nuwro
export LD_LIBRARY_PATH=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/pythia6_nuwro:$LD_LIBRARY_PATH
export GSLLIB=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/gsl/lib
export GSLINC=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/gsl/include
export LD_LIBRARY_PATH=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/gsl/lib:$LD_LIBRARY_PATH
export PATH=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/gsl/bin:$PATH
export ROOTSYS=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/build_root
export PATH=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/build_root/bin:$PATH
export LD_LIBRARY_PATH=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/build_root/lib:$LD_LIBRARY_PATH
export LOG4CPP_INC=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/log4cpp/include
export LOG4CPP_LIB=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/log4cpp/lib
export LD_LIBRARY_PATH=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/log4cpp/lib:$LD_LIBRARY_PATH
export LHAPATH=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/lhapdf
export LHAPDF_INC=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/lhapdf/include
export LHAPDF_LIB=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/lhapdf/lib
export LD_LIBRARY_PATH=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/lhapdf/lib:$LD_LIBRARY_PATH
export ROOMU_SYS=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/RooMUHistos
export LD_LIBRARY_PATH=/sps/t2k/sdolan/software/GENIE/lamp/GENIESupport/RooMUHistos/lib:$LD_LIBRARY_PATH
export PATH=$ROOMU_SYS/bin:$PATH
export GENIE=/sps/t2k/sdolan/generators/genie/3_0_SuSADevGit/GENIE_SuSADev
export LD_LIBRARY_PATH=/sps/t2k/sdolan/generators/genie/3_0_SuSADevGit/GENIE_SuSADev/lib:$LD_LIBRARY_PATH
export PATH=/sps/t2k/sdolan/generators/genie/3_0_SuSADevGit/GENIE_SuSADev/bin:$PATH