#!/bin/sh
# -*- sh-indentation: 3 -*-
#
# genie-config a la ROOT's root-config
#

########################### GENIE Libraries Directory:

libdir=$GENIE/lib

########################### GENIE src top level directory:

srcdir=$GENIE/src

########################### GENIE Libraries;

libs="-L $libdir -lGAlgorithm -lGBaryonResonance -lGBase -lGBodekYang -lGCharm \
 -lGCrossSections -lGDecay -lGHEP -lGEVGCore -lGEVGModules -lGEVGDrivers \
 -lGFragmentation -lGInteraction -lGInvMuDecay -lGLlewellynSmith -lGMessenger\
 -lGNtuple -lGNuclear -lGNumerical -lGPartonModel -lGPDG -lGPDF\
 -lGRadiative -lGRegistry -lGReinSeghal -lGUtils"

if test "$GOPT_ENABLE_GEOM_DRIVERS" = "YES"; then
  libs="$libs -lGGeo"
fi
if test "$GOPT_ENABLE_FLUX_DRIVERS" = "YES"; then
  libs="$libs -lGFluxDrivers"
fi
if test "$GOPT_ENABLE_GEANT_INTERFACE" = "YES"; then
  libs="$libs -lGG4I"
fi
if test "$GOPT_ENABLE_VALIDITY_DOC" = "YES"; then
  libs="$libs -lGValidityDoc"
fi
if test "$GOPT_ENABLE_VIEWER" = "YES"; then
  libs="$libs -lGViewer"
fi
if test "$GOPT_ENABLE_MUELOSS" = "YES"; then
  libs="$libs -lGMuELoss"
fi

########################### GENIE Dictionaries;

dictionaries="  $srcdir/Algorithm/_ROOT_DICT_Algorithm.o \
		$srcdir/BaryonResonance/_ROOT_DICT_BaryonResonance.o \
                $srcdir/Base/_ROOT_DICT_Base.o \
                $srcdir/BodekYang/_ROOT_DICT_BodekYang.o \
                $srcdir/Charm/_ROOT_DICT_Charm.o \
                $srcdir/CrossSections/_ROOT_DICT_CrossSections.o \
                $srcdir/Decay/_ROOT_DICT_Decay.o \
                $srcdir/EVGCore/_ROOT_DICT_EVGCore.o \
                $srcdir/EVGModules/_ROOT_DICT_EVGModules.o \
                $srcdir/EVGDrivers/_ROOT_DICT_EVGDrivers.o \
                $srcdir/Fragmentation/_ROOT_DICT_Fragmentation.o \
                $srcdir/Interaction/_ROOT_DICT_Interaction.o \
                $srcdir/InverseMuonDecay/_ROOT_DICT_InverseMuDecay.o \
                $srcdir/LlewellynSmith/_ROOT_DICT_LlewellynSmith.o \
                $srcdir/GHEP/_ROOT_DICT_GHEP.o \
                $srcdir/Ntuple/_ROOT_DICT_Ntuple.o \
                $srcdir/Nuclear/_ROOT_DICT_Nuclear.o \
                $srcdir/Numerical/_ROOT_DICT_Numerical.o \
                $srcdir/PartonModel/_ROOT_DICT_PartonModel.o \
                $srcdir/PDG/_ROOT_DICT_PDG.o \
                $srcdir/PDF/_ROOT_DICT_PDF.o \
		$srcdir/Radiative/_ROOT_DICT_Radiative.o \
                $srcdir/Registry/_ROOT_DICT_Registry.o \
                $srcdir/ReinSeghal/_ROOT_DICT_ReinSeghal.o \
                $srcdir/Utils/_ROOT_DICT_Utils.o"

if test "$GOPT_ENABLE_GEOM_DRIVERS" = "YES"; then
  dictionaries="$dictionaries $srcdir/Geo/_ROOT_DICT_Geo.o"
fi
if test "$GOPT_ENABLE_FLUX_DRIVERS" = "YES"; then
  dictionaries="$dictionaries $srcdir/FluxDrivers/_ROOT_DICT_FluxDrivers.o"
fi
if test "$GOPT_ENABLE_VALIDITY_DOC" = "YES"; then
  dictionaries="$dictionaries $srcdir/ValidityDoc/_ROOT_DICT_ValidityDoc.o"
fi
if test "$GOPT_ENABLE_VIEWER" = "YES"; then
  dictionaries="$dictionaries $srcdir/Viewer/_ROOT_DICT_Viewer.o"
fi
if test "$GOPT_ENABLE_MUELOSS" = "YES"; then
  dictionaries="$dictionaries $srcdir/MuELoss/_ROOT_DICT_MuELoss.o"
fi

usage="\
Usage: genie-config [--libs] [--dicts] [--libdir] [--topsrcdir]" 

if test $# -eq 0; then
   echo "${usage}" 1>&2
   exit 1
fi

out=""

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *)    optarg= ;;
  esac

  case $1 in
    --libs)
      ### Output GENIE libraries
      out="$out $libs"
      ;;
    --dicts)
      ### Output GENIE dictionaries
      out="$out $dictionaries"
      ;;
    --libdir)
      ### Output GENIE libdir
      out="$out $libdir"
      ;;
    --topsrcdir)
      ### Output GENIE top level src directory
      out="$out $srcdir"
      ;;
  esac
  shift
done

echo $out
