#! /usr/bin/perl -w

# Reads building options from your environment and writes them
# down to the 'build.options' file.
# Consult this file if you have any doubt on how was GENIE build
# was performed...

$GENIE = $ENV{'GENIE'};

die ("Not even the GENIE environmental variable is defined!") unless defined $GENIE;

$SRT_ENV_SET   = $ENV{'SRT_ENV_SET'};
$ROOTSYS       = $ENV{'ROOTSYS'};
$CERNLIB       = $ENV{'CERNLIB'};
$PYTHIA6       = $ENV{'PYTHIA6'};
$LIBXML2_INC   = $ENV{'LIBXML2_INC'};
$LIBXML2_LIB   = $ENV{'LIBXML2_LIB'};
$LOG4CPP_INC   = $ENV{'LOG4CPP_INC'};
$LOG4CPP_LIB   = $ENV{'LOG4CPP_LIB'};
$NEUGEN3PATH   = $ENV{'NEUGEN3PATH'};
$GPROFILER_LIB = $ENV{'GPROFILER_LIB'};
$DOXYGEN       = $ENV{'DOXYGEN'};
$CLHEP_INC     = $ENV{'CLHEP_INC'};
$CLHEP_LIB     = $ENV{'CLHEP_LIB'};
$GEANT4_INC    = $ENV{'GEANT4_INC'};
$GEANT4_LIB    = $ENV{'GEANT4_LIB'};

$PATH            = $ENV{'PATH'};
$LD_LIBRARY_PATH = $ENV{'LD_LIBRARY_PATH'};

$GOPT_ENABLE_NUVALIDATOR     = $ENV{'GOPT_ENABLE_NUVALIDATOR'};
$GOPT_ENABLE_NEUGEN          = $ENV{'GOPT_ENABLE_NEUGEN'};
$GOPT_ENABLE_GEANT_INTERFACE = $ENV{'GOPT_ENABLE_GEANT_INTERFACE'};
$GOPT_ENABLE_FLUX_DRIVERS    = $ENV{'GOPT_ENABLE_FLUX_DRIVERS'};
$GOPT_ENABLE_GEOM_DRIVERS    = $ENV{'GOPT_ENABLE_GEOM_DRIVERS'};
$GOPT_ENABLE_PROFILER        = $ENV{'GOPT_ENABLE_PROFILER'};
$GOPT_ENABLE_DOXYGEN_DOC     = $ENV{'GOPT_ENABLE_DOXYGEN_DOC'};
$GOPT_ENABLE_TEST            = $ENV{'GOPT_ENABLE_TEST'};
$GOPT_ENABLE_VALIDITY_DOC    = $ENV{'GOPT_ENABLE_VALIDITY_DOC'};
$GOPT_ENABLE_VIEWER          = $ENV{'GOPT_ENABLE_VIEWER'};
$GOPT_ENABLE_MUELOSS         = $ENV{'GOPT_ENABLE_MUELOSS'};

# suppress PERL warnings when using undefined variables

$SRT_ENV_SET   = "" unless defined $SRT_ENV_SET;
$ROOTSYS       = "" unless defined $ROOTSYS;
$CERNLIB       = "" unless defined $CERNLIB;
$PYTHIA6       = "" unless defined $PYTHIA6;
$LIBXML2_INC   = "" unless defined $LIBXML2_INC;
$LIBXML2_LIB   = "" unless defined $LIBXML2_LIB;
$LOG4CPP_INC   = "" unless defined $LOG4CPP_INC;
$LOG4CPP_LIB   = "" unless defined $LOG4CPP_LIB;
$NEUGEN3PATH   = "" unless defined $NEUGEN3PATH;
$GPROFILER_LIB = "" unless defined $GPROFILER_LIB;
$DOXYGEN       = "" unless defined $DOXYGEN;
$CLHEP_INC     = "" unless defined $CLHEP_INC;
$CLHEP_LIB     = "" unless defined $CLHEP_LIB;
$GEANT4_INC    = "" unless defined $GEANT4_INC;
$GEANT4_LIB    = "" unless defined $GEANT4_LIB;

# save build options

$BLD_OPT = "$GENIE/src/build.options";
open(OPT, ">$BLD_OPT") 
    or die("Can not open build.options file to save your build settings");

print OPT "[The GENIE spy reports]\n\n";
print OPT "This was your environment last time you typed 'gmake' in $GENIE/src:\n\n";

print OPT "\$SRT_ENV_SET   -> $SRT_ENV_SET\n";
print OPT "\$ROOTSYS       -> $ROOTSYS\n";
print OPT "\$CERNLIB       -> $CERNLIB\n";
print OPT "\$PYTHIA6       -> $PYTHIA6\n";
print OPT "\$LIBXML2_INC   -> $LIBXML2_INC\n";
print OPT "\$LIBXML2_LIB   -> $LIBXML2_LIB\n";
print OPT "\$LOG4CPP_INC   -> $LOG4CPP_INC\n";
print OPT "\$LOG4CPP_LIB   -> $LOG4CPP_LIB\n";
print OPT "\$NEUGEN3PATH   -> $NEUGEN3PATH\n";
print OPT "\$GPROFILER_LIB -> $GPROFILER_LIB\n";
print OPT "\$DOXYGEN       -> $DOXYGEN\n";
print OPT "\$CLHEP_INC     -> $CLHEP_INC\n";
print OPT "\$CLHEP_LIB     -> $CLHEP_LIB\n";
print OPT "\$GEANT4_INC    -> $GEANT4_INC\n";
print OPT "\$GEANT4_LIB    -> $GEANT4_LIB\n\n";

print OPT "\$PATH            -> $PATH\n\n";

print OPT "\$LD_LIBRARY_PATH -> $LD_LIBRARY_PATH\n\n";

print OPT "\$GOPT_ENABLE_NUVALIDATOR     -> $GOPT_ENABLE_NUVALIDATOR\n";
print OPT "\$GOPT_ENABLE_NEUGEN          -> $GOPT_ENABLE_NEUGEN\n";
print OPT "\$GOPT_ENABLE_FLUX_DRIVERS    -> $GOPT_ENABLE_FLUX_DRIVERS\n";
print OPT "\$GOPT_ENABLE_GEOM_DRIVERS    -> $GOPT_ENABLE_GEOM_DRIVERS\n";
print OPT "\$GOPT_ENABLE_GEANT_INTERFACE -> $GOPT_ENABLE_GEANT_INTERFACE\n";
print OPT "\$GOPT_ENABLE_PROFILER        -> $GOPT_ENABLE_PROFILER\n";
print OPT "\$GOPT_ENABLE_DOXYGEN_DOC     -> $GOPT_ENABLE_DOXYGEN_DOC\n";
print OPT "\$GOPT_ENABLE_TEST            -> $GOPT_ENABLE_TEST\n";
print OPT "\$GOPT_ENABLE_VALIDITY_DOC    -> $GOPT_ENABLE_VALIDITY_DOC\n";
print OPT "\$GOPT_ENABLE_VIEWER          -> $GOPT_ENABLE_VIEWER\n";
print OPT "\$GOPT_ENABLE_MUELOSS         -> $GOPT_ENABLE_MUELOSS\n";

close(OPT);

