//____________________________________________________________________________
/*!

\class   genie::IMDInteractionListGenerator

\brief   Concrete implementations of the InteractionListGeneratorI interface.
         Generate a list of all the Interaction (= event summary) objects that
         can be generated by the IMD EventGenerator.

\author  Costas Andreopoulos <C.V.Andreopoulos@rl.ac.uk>
         CCLRC, Rutherford Appleton Laboratory

\created July 13, 2005

*/
//____________________________________________________________________________

#ifndef _IMD_INTERACTION_GENERATOR_H_
#define _IMD_INTERACTION_GENERATOR_H_

#include "EVGCore/InteractionListGeneratorI.h"

namespace genie {

class IMDInteractionListGenerator : public InteractionListGeneratorI {

public :

  IMDInteractionListGenerator();
  IMDInteractionListGenerator(const char * param_set);
  ~IMDInteractionListGenerator();

  //-- define the InteractionListGeneratorI interface

  InteractionList * CreateInteractionList(const InitialState & init) const;
};

}      // genie namespace

#endif // _IMD_INTERACTION_GENERATOR_H_
