//____________________________________________________________________________
/*!

\class   genie::QELInteractionListGenerator

\brief   Concrete implementations of the InteractionListGeneratorI interface.
         Generate a list of all the Interaction (= event summary) objects that
         can be generated by the QEL EventGenerator.

\author  Costas Andreopoulos <C.V.Andreopoulos@rl.ac.uk>
         CCLRC, Rutherford Appleton Laboratory

\created May 13, 2005

*/
//____________________________________________________________________________

#ifndef _QEL_INTERACTION_GENERATOR_H_
#define _QEL_INTERACTION_GENERATOR_H_

#include "EVGCore/InteractionListGeneratorI.h"

namespace genie {

class QELInteractionListGenerator : public InteractionListGeneratorI {

public :

  QELInteractionListGenerator();
  QELInteractionListGenerator(string config);
  ~QELInteractionListGenerator();

  //-- define the InteractionListGeneratorI interface

  InteractionList * CreateInteractionList(const InitialState & init) const;

private:

  InteractionList * CreateInteractionListCC(const InitialState & init) const;
  InteractionList * CreateInteractionListNC(const InitialState & init) const;
};

}      // genie namespace

#endif // _QEL_INTERACTION_GENERATOR_H_
