//____________________________________________________________________________
/*!

\class   genie::RESInteractionListGenerator

\brief   Concrete implementations of the InteractionListGeneratorI interface.
         Generate a list of all the Interaction (= event summary) objects that
         can be generated by the RES EventGenerator.

\author  Costas Andreopoulos <C.V.Andreopoulos@rl.ac.uk>
         CCLRC, Rutherford Appleton Laboratory

\created May 13, 2005

*/
//____________________________________________________________________________

#ifndef _RES_INTERACTION_LIST_GENERATOR_H_
#define _RES_INTERACTION_LIST_GENERATOR_H_

#include "EVGCore/InteractionListGeneratorI.h"
#include "Interaction/SppChannel.h"

namespace genie {

class RESInteractionListGenerator : public InteractionListGeneratorI {

public :

  RESInteractionListGenerator();
  RESInteractionListGenerator(string config);
  ~RESInteractionListGenerator();

  //-- define the InteractionListGeneratorI interface

  InteractionList * CreateInteractionList(const InitialState & init) const;

private:

  void AddFinalStateInfo (Interaction * i, SppChannel_t chan) const;
};

}      // genie namespace

#endif // _RES_INTERACTION_LIST_GENERATOR_H_
