#
# Makefile for GENIE Neutrino Generator
#
# Author: Costas Andreopoulos <costas.andreopoulos \at stfc.ac.uk>
#

SHELL    = /bin/sh
NAME     = all
MAKEFILE = Makefile

# Include machine specific flags and locations (inc. files & libs)
#
include $(GENIE)/src/make/Make.include

PACKAGE           = Conventions
DICTIONARY        = 
LIBNAME           = 
EXTRA_EXT_LIBS    =

all     : 
install : install-inc 

# Include standard package makefile targets
#
include $(GENIE)/src/make/Make.std-package-targets

FORCE:

