#!/bin/bash
#
#----------------------------------------------------------------
# An example bash shell script for setting up the environment for
# building/using GENIE
#
# Costas Andreopoulos <C.V.Andreopoulos@rl.ac.uk>
#----------------------------------------------------------------
#
# See $GENIE/src/Make.include for a definition of these variables
# and change them to match your machine's package organization.
# Note: not all of these are mandatory (see below)

#----------------------------------------------------------------
#                         Setting paths
#----------------------------------------------------------------

# [mandatory] 

export GENIE=/home/costas/MC/GENIE
export ROOTSYS=/usr/local/src/root-4.04.02b
export CERNLIB=/usr/local/src/CERN/2004/lib
export PYTHIA6=/home/costas/MC/PYTHIA/v-6
export LIBXML2_INC=/usr/include/libxml2
export LIBXML2_LIB=/usr/lib
export LOG4CPP_INC=/usr/local/src/log4cpp/include
export LOG4CPP_LIB=/usr/local/lib

# [optional]
#   (depending on which features you enable)

#---  You only really need to set NEUGEN3PATH is you plan to enable
#---  GENIE's NuValidator (by setting GOPT_ENABLE_NUVALIDATOR=YES)
export NEUGEN3PATH=/home/costas/MC/neugen3

#---  You only really need to set GIBUU is you want to enable the
#---  GENIE/GIBUU interface (by setting GOPT_ENABLE_GIBUU=YES)
export GIBUU_LIB=

#--- You only really need to set GPROFILER is you plan to enable
#--- Google's profiling tool (by setting GOPT_ENABLE_PROFILER=YES)
export GPROFILER_LIB=/usr/local/lib

#--- You only really need to set DOXYGEN is you plan to enable
#--- GENIE's Doxygen documentation (by setting GOPT_ENABLE_DOXYGEN_DOC=YES)
export DOXYGEN=/usr/local/bin/doxygen

# this adds the necessary paths to your PATH and LD_LIBRARY_PATH
# environmental variables:
export PATH=${PATH}:${ROOTSYS}/bin:${GENIE}/bin
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ROOTSYS}/lib:${GENIE}/lib

#----------------------------------------------------------------
#                    Setting build options
#----------------------------------------------------------------

export GOPT_ENABLE_PROFILER=NO
export GOPT_ENABLE_NUVALIDATOR=YES 
export GOPT_ENABLE_NEUGEN=YES
export GOPT_ENABLE_GIBUU=NO
export GOPT_ENABLE_FLUX_DRIVERS=YES
export GOPT_ENABLE_GEOM_DRIVERS=YES
export GOPT_ENABLE_DOXYGEN_DOC=NO 
export GOPT_ENABLE_TEST=NO 
export GOPT_ENABLE_VIEWER=NO
export GOPT_ENABLE_MUELOSS=NO

#----------------------------------------------------------------
#                           Report
#----------------------------------------------------------------

echo
echo "Setting up the environment for GENIE:"
echo "-------------------------------------"

if [ ! -z "SRT_ENV_SET" ]; 
then
 echo "srt_setup --unsetup"
 srt_setup --unsetup
fi

echo "GENIE       -> " ${GENIE}
echo "ROOTSYS     -> " ${ROOTSYS}
echo "NEUGEN3PATH -> " ${NEUGEN3PATH}
echo "CERNLIB     -> " ${CERNLIB}
echo "PYTHIA      -> " ${PYTHIA6}
echo "GIBUU_LI    -> " ${GIBUU_LIB}
echo "LIBXML2_INC -> " ${LIBXML2_INC}
echo "LIBXML2_LIB -> " ${LIBXML2_LIB}
echo "LOG4CPP_INC -> " ${LOG4CPP_INC}
echo "LOG4CPP_LIB -> " ${LOG4CPP_LIB}
echo
echo "GENIE building options:"
echo "-----------------------"
echo "Enabling GENIE's NuValidator       -> " ${GOPT_ENABLE_NUVALIDATOR}
echo "Enabling GENIE's NeuGen facade     -> " ${GOPT_ENABLE_NEUGEN}
echo "Enabling GENIE/GIBUU interface     -> " ${GOPT_ENABLE_GIBUU}
echo "Enabling GENIE's flux drivers      -> " ${GOPT_ENABLE_FLUX_DRIVERS}
echo "Enabling GENIE's geometry drivers  -> " ${GOPT_ENABLE_GEOM_DRIVERS}
echo "Enabling Google profiler           -> " ${GOPT_ENABLE_PROFILER}
echo "Enabling Doxygen doc generation    -> " ${GOPT_ENABLE_DOXYGEN_DOC}
echo "Enabling GENIE test programs       -> " ${GOPT_ENABLE_TEST}
echo "Enabling GENIE Feynman/GHEP viewer -> " ${GOPT_ENABLE_VIEWER}
echo "Enabling MuELoss utility package   -> " ${GOPT_ENABLE_MUELOSS}

echo

