#!/bin/sh
# -*- sh-indentation: 3 -*-
#
# genie-config a la ROOT's root-config
#

### GENIE config options:
. $GENIE/src/make/Make.config_no_paths

### GENIE libraries path:
libdir=$GENIE/lib

### GENIE src top level directory:
srcdir=$GENIE/src

### GENIE libraries;

# the following libs should always be there
libs="-L$libdir -lGAlgorithm -lGBaryonResonance -lGBase -lGBodekYang -lGCharm -lGCoh -lGDfrc -lGDIS \
 -lGCrossSections -lGDecay -lGElas -lGElFF -lGHEP -lGEVGCore -lGEVGModules -lGEVGDrivers -lGGiBUU \
 -lGHadronTransp -lGFragmentation -lGInteraction -lGLlewellynSmith -lGMEC \
 -lGMessenger -lGNuGamma -lGNuE -lGNtuple -lGNuclear -lGNumerical -lGQPM -lGPDG -lGPDF\
 -lGQEL -lGRES -lGRegistry -lGReinSehgal -lGSingleKaon -lGUtils -lGVHE"

# the following libs should only be there if an appropriate option was enabled at the configuration step
if test "$GOPT_ENABLE_GEOM_DRIVERS" = "YES"; then
  libs="$libs -lGGeo"
fi
if test "$GOPT_ENABLE_FLUX_DRIVERS" = "YES"; then
  libs="$libs -lGFluxDrivers"
fi
if test "$GOPT_ENABLE_VLE_EXTENSION" = "YES"; then
  libs="$libs -lGVLE"
fi
if test "$GOPT_ENABLE_MUELOSS" = "YES"; then
  libs="$libs -lGMuELoss"
fi
if test "$GOPT_ENABLE_RWGHT" = "YES"; then
  libs="$libs -lGReWeight"
fi
if test "$GOPT_ENABLE_NUCLEON_DECAY" = "YES"; then
  libs="$libs -lGNucleonDecay"
fi

### Usage
usage="\
Usage: genie-config [--libs] [--libdir] [--topsrcdir]" 

if test $# -eq 0; then
   echo "${usage}" 1>&2
   exit 1
fi

out=""

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *)    optarg= ;;
  esac

  case $1 in
    --libs)
      ### GENIE libraries
      out="$out $libs"
      ;;
    --libdir)
      ### Output GENIE libdir
      out="$out $libdir"
      ;;
    --topsrcdir)
      ### Output GENIE top level src directory
      out="$out $srcdir"
      ;;
  esac
  shift
done

echo $out
